apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tyt2lf24u-nodejs
  janus-idp.io/tekton: tyt2lf24u-nodejs
  backstage.io/kubernetes-id: tyt2lf24u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tyt2lf24u-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
